# permissions for end users to edit childas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: childa-editor-role
rules:
- apiGroups:
  - dummy.example.com
  resources:
  - childas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dummy.example.com
  resources:
  - childas/status
  verbs:
  - get
