# permissions for end users to view childas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: childa-viewer-role
rules:
- apiGroups:
  - dummy.example.com
  resources:
  - childas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dummy.example.com
  resources:
  - childas/status
  verbs:
  - get
