# permissions for end users to view heads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: head-viewer-role
rules:
- apiGroups:
  - dummy.example.com
  resources:
  - heads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dummy.example.com
  resources:
  - heads/status
  verbs:
  - get
